version: '3.7'
services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: exchange_redis_container
    ports:  
      - "6379:6379"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    network_mode: host
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


volumes:
  pgdata:
