version: '3.7'
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    # environment:
    #   - ${POSTGRES_NAME:?}
    #   - ${POSTGRES_HOST:?}
    #   - ${POSTGRES_USER:?}
    #   - ${POSTGRES_PASSWORD:?}
    #   - ${POSTGRES_DB:?}
    ports:
      - "5432:5432"
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: exchange_redis_container
    ports:  
      - "6379:6379"
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    networks:
      - app_network
    restart: on-failure
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  pgdata:
