"""Initial migration

Revision ID: a5dd10b65d68
Revises: 
Create Date: 2024-10-31 23:44:45.699847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5dd10b65d68"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Currencies",
        sa.Column("oid", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sign", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_table(
        "ExchangeRates",
        sa.Column("oid", sa.String(), nullable=False),
        sa.Column("base_currency_oid", sa.String(), nullable=True),
        sa.Column("target_currency_oid", sa.String(), nullable=True),
        sa.Column("rate", sa.DECIMAL(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_currency_oid"],
            ["Currencies.oid"],
        ),
        sa.ForeignKeyConstraint(
            ["target_currency_oid"],
            ["Currencies.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ExchangeRates")
    op.drop_table("Currencies")
    # ### end Alembic commands ###
